server:
  image: vimagick/shadowsocks-libev
  ports:
    - "8388:8388"
  environment:
    - METHOD=chacha20
    - PASSWORD=secret
  restart: always
  container_name: shadowsocks-libev-server

client:
  image: vimagick/shadowsocks-libev
  command: ss-local -s foobar.site -p 8388 -b 0.0.0.0 -l 1080 -k secret -m chacha20
  ports:
    - "1080:1080"
  restart: always
  container_name: shadowsocks-libev-client
